### ISSUE TITLE
DBRouteCache: -isRoute(startPoint: Waypoint, endPoint:Waypoint):Boolean

### ISSUE THREAD

**Issue by perrymatthew** [perrymatthew/cos301_Longsword_Navigation#15]
Method

**Comment by perrymatthew** [comment]
this should be a private function in the DBRouteCache.java file, not a separate file. I'll move it for you

**Comment by JON-Nathan** [comment]
Thank you so much, so I was suppose to just append it to the bottom of the
DBRouteCache.java file

**Comment by perrymatthew** [comment]
yes, you can have a look at the DBRouteCache.java file now and see. I'll move this to done
