### ISSUE TITLE
SQLRouteCache +getCachedRoute(String route)

### ISSUE THREAD

**Issue by Mazz1es** [perrymatthew/cos301_Longsword_Navigation#93]

**Comment by perrymatthew** [comment]
could you please give more clarity on what this method's purpose is? 
I don't understand the comment in the code: "Get route function to get the route to the SQL DB"

**Comment by perrymatthew** [comment]
if this method is meant to return a route that's in the cache, the parameters should rather be 2 strings, start and end point. String route implies that its gonna be a JSON string of the entire route which would be redundant.
